### ISSUE TITLE
Simplify project integration with scala-cli

### ISSUE THREAD

**Issue by prolativ** [scalameta/metals-feature-requests#299] opened 2022-09-06 13:45 UTC
### Is your feature request related to a problem? Please describe.

Setting up metals to work with a scala-cli project (also containing just a single file) requires a few manual steps, which are not obvious.
A typical flow:
1. Run `scala-cli setup-ide .`
2. Click `Connect to build server`

The integration with scala-cli (especially for single file projects) should be seamless.

### Describe the solution you'd like

Some possibilities for improvements:
- make scala-cli the default build server if no other build configuration (like `build.sbt` or `build.sc`) is found or even use it instead of the default presentation compiler for single files
- make `Import build` command handle running `scala-cli setup-ide` and connecting to the server under the hood
- suggest importing the build using scala-cli (as it's done e.g. for sbt builds)

### Describe alternatives you've considered

At least improve the documentation (scala-cli is not even listed in the `Build tools` section).

### Search terms

scala-cli

**Comment by kpodsiad** [comment] 2022-09-06 16:03
> (scala-cli is not even listed in the `Build tools` section).

it's a feature, not a bug 😆
<img width="1107" alt="Screenshot 2022-09-06 at 17 59 31" src="https://user-images.githubusercontent.com/37124721/188682203-1875b05c-d66e-4564-be43-d20f78ac9294.png">

**Comment by tanishiking** [comment] 2022-09-07 04:46
Here's a conversation from discord, most of us are positive to the proposal :)
https://discord.com/channels/632642981228314653/718047292749381662/1016717087810519060

```
Tomasz Godzik — Yesterday at 11:30 PM
Hey, what are people opinions on https://github.com/scalameta/metals-feature-requests/issues/299 ?

Chris Kipp — Yesterday at 11:32 PM
At least improve the documentation (scala-cli is not even listed in the Build tools section).
that's because we were told it wasn't a build tool

velvetbaldmime — Yesterday at 11:33 PM
😄
I'm a user of scala-cli and generally in favour of the proposal.
As long as it's on track to become scala replacement

gabro — Yesterday at 11:34 PM
There’s a SIP for it

velvetbaldmime — Yesterday at 11:35 PM
There’s a SIP for it
is that a threat

Chris Kipp — Yesterday at 11:35 PM
I think I commented this earlier on in Alex's pr maybe, but I'd have to dig back. It might make sense to also have a ScalaCliBuildTool that extends BuildServerProvider because we'd get some things for free then like generateBspCOnfig, information on whether the workspace supports it etc
then just like the other tools it could automatically run scala-cli setup-ide . when you choose it as a build server 
the problem is detecting if a workspace is meant to be a scala-cli workspace, or even if it's maybe nested in an existing sbt project or something
the "start", "stop" commands that are specific to scala-cli I think are a mistake tbh, we special case it when I wish we could only rely on BSP discovery
however I know there is a tradeoff with then that being harder if you have a mixed say sbt/scala-cli project
since they user would have to do a bsp switch when switching between sources
and that would bring all sorts of confusion
all in all, I'm totally game for a more seamless integration

tanishiking — Yesterday at 11:38 PM
I basically agree with @velvetbaldmime 
I see many Scala beginners try to run Metals without any build settings (sbt nor mill) and confused Metals doesn't work well. But I would wait the SIP (about scala-cli as scala command) is accepted or not before going further.
Also, yeah, it would be definitely a problem.
the problem is detecting if a workspace is meant to be a scala-cli workspace, or even if it's maybe nested in an existing sbt project or something
 
gabro — Yesterday at 11:42 PM
I agree waiting for the SIP to get the “design” accepted is a good idea. Once that’s done, the details of how it should work should be finalized

Tomasz Godzik — Today at 12:00 AM
@Chris Kipp there is another feature request to support multiple tools in ,bsp so maybe that would be a better long term solution? We could allow people to start all the BSP servers defined

Chris Kipp — Today at 12:02 AM
yea indeed that'd be neat

vadim chelyhov — Today at 12:06 AM
I think it shouldn't be a problem if we add Import Build as scala-cli projects suggestion as a fallback option even without waiting SIP approval. We anyway don't have any alternative to it if there were no other build tools detected.
```

**Comment by prolativ** [comment] 2022-09-07 07:09
@kpodsiad you're right - scala-cli is not a build tool so it needs its own section 😆 Or we could make the integration so seamless that no documentation would be needed 😉
And I agree with @dos65 - there's no need to wait for the SIP, which just changes the behaviour of `scala` in the command line. If we use `scala-cli` directly, the SIP should have no impact.

**Comment by tanishiking** [comment] 2022-09-07 08:24
> there's no need to wait for the SIP, which just changes the behaviour of scala in the command line.

I think the SIP means more than "just changing the behavior of scala in the command line", I was thinking it's more like "is scala-cli accepted and being recommended as an official cli tool for Scala development in the whole Scala community".

If the SIP is accepted, that means Scala community accepted `scala-cli` as an official tool, so we'll definitely in
Even if SIP is not accepted, as long as `scala-cli` will be recommended as an "official" tool for Scala development, we can go for it.

However, supporting this feature before SIP goes sounds like, Metals is advertising scala-cli as an official Scala tool. 
I proposed waiting for SIP to express scalameta's fairness as a community-driven OSS toolchain, and I was just cautious about going further.

(Don't get me wrong, I believe scala-cli is a great tool, and I want scala-cli to be accepted as an "official" tool 😆 )

**Comment by tanishiking** [comment] 2022-09-07 08:49
I believe SIP means more than "just changes the behavior of scala in the command line", it's more like "is scala-cli accepted as an official tool".
I was just too cautious about going further before `scala-cli` is widely accepted by the community, because using `scala-cli` as a build server by default might mean, forcing Scala beginners to use `scala-cli`.
That's why I proposed to wait for SIP before going further.

But, now I'm on the fence. Supporting `scala-cli` as a build-server by default helps `scala-cli` to stand out as an "official" scala tool. (I am personally supportive of `scala-cli` being an "official" tool). 😆

**Comment by kasiaMarek** [comment] 2023-12-04 14:36
Resolved by https://github.com/scalameta/metals/pull/5221.

**Closed as completed by kasiaMarek** 2023-12-04 14:36 UTC
