### ISSUE TITLE
Implement `textDocument/codeAction`

### ISSUE THREAD

**Issue by gvolpe** [scalameta/metals-feature-requests#22] opened 2019-05-03 08:10 UTC
https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction

**Describe the solution you'd like**
- It will allows us to perform actions suggested by the compiler such as remove imports or refactor a piece of code.

**Search terms**:
- type not found: add import to the top
- remove unused imports
- inline method
- move definition to the top

**Comment by gabro** [comment] 2019-05-03 08:11
Hi @gvolpe! That's indeed a good feature to have, could it be a duplicate of #18?

**Comment by gvolpe** [comment] 2019-05-03 08:17
Hi @gabro ! I think #18 is focusing on very specific tasks whereas this is requesting the protocol function `codeAction` to be implemented.

For example, with `codeAction` implemented we should be able to remove unused imports which is not mentioned in #18. 

Maybe #18 is a part of this request?

**Comment by olafurpg** [comment] 2019-05-03 08:28
Thanks for reporting! This is indeed a duplicate of #18, which would be implemented via code actions (although it's wasn't mentioned in the description, I've updated it now). The main challenge for code actions is to implement the refactorings themselves, the actual protocol `textDocument/codeAction` endpoint is not very useful on its own.

**Closed by olafurpg** 2019-05-03 08:28 UTC

**Comment by gvolpe** [comment] 2019-05-03 09:35
Got it! Thanks for clarifying and sorry for the duplication, I'll upvote #18 then :)
